"""Deterministic trip cost arithmetic.

Shared by the itinerary and budget agents so there is exactly one place that
knows the unit conventions — which are the easy thing to get wrong:

    flight fares      PER PERSON      -> scale by travellers
    lodging rates     WHOLE PARTY     -> scale by nights only
    activity costs    PER PERSON      -> scale by travellers

Nothing here is ever generated by a model.
"""

from datetime import date
from typing import Optional

from models import CostBreakdown, TripState


# Kinds that do not charge admission, from the OpenStreetMap tag rather than
# from a model's belief about admission policy. Two prompt rules used to govern
# this and they contradicted each other; a tag lookup has no such problem.
FREE_KINDS = {
    "viewpoint", "attraction", "city_gate", "church", "chapel", "cathedral",
    "square", "plaza", "park", "garden", "memorial", "artwork", "monument",
    "ruins", "aqueduct", "wall", "bridge", "fountain", "market",
}

# Restaurants and cafes charge, but their cost is FOOD, which the budget
# reports as excluded. Pricing them in the itinerary would double-count.
MEAL_KINDS = {"restaurant", "cafe", "bar", "pub", "fast_food", "food_court"}


def is_meal(kind: str | None, category: str | None = None) -> bool:
    return (kind or "").lower() in MEAL_KINDS or (category or "") == "food"


def is_free_kind(kind: str | None, category: str | None = None) -> bool:
    """True when a place should carry no cost in the itinerary.

    Meals count as free HERE because food is budgeted separately — not because
    eating is free.
    """
    if is_meal(kind, category):
        return True
    return (kind or "").lower() in FREE_KINDS


def nights(req) -> int:
    """Nights from the trip dates.

    Never derived from the weather agent's day count: if weather failed or
    returned partial data, lodging would silently vanish from the total.
    """
    try:
        return max(
            (date.fromisoformat(req.end_date) - date.fromisoformat(req.start_date)).days,
            0,
        )
    except ValueError:
        return 0


def tier_for(req) -> str:
    """Which price tier to cost the trip at.

    A stated budget is a cap, and a cap is best met from the floor, so cost the
    cheapest options. With no budget there is nothing to respect and costing the
    cheapest would imply a bargain trip nobody asked for — so take the middle
    option instead.
    """
    return "cheapest" if req.budget_usd is not None else "mid"


def pick(values: list[float], tier: str) -> Optional[float]:
    """Cheapest or middle value from a price list."""
    if not values:
        return None
    ordered = sorted(values)
    if tier == "mid":
        return ordered[len(ordered) // 2]
    return ordered[0]


def flight_total(
    state: TripState, travelers: int, tier: str = "cheapest"
) -> Optional[float]:
    """Selected fare scaled to the whole party. Fares are per person."""
    flight = state.get("flight")
    fares = [o.price_usd for o in flight.options] if flight and flight.options else []
    chosen = pick(fares, tier)
    return round(chosen * travelers, 2) if chosen is not None else None


def lodging_total(
    state: TripState, night_count: int, tier: str = "cheapest"
) -> Optional[float]:
    """Selected nightly rate x nights. Rates already cover the whole party."""
    hotels = state.get("hotels")
    rates = (
        [h.price_per_night_usd for h in hotels.options]
        if hotels and hotels.options
        else []
    )
    chosen = pick(rates, tier)
    return round(chosen * night_count, 2) if chosen is not None else None


def activities_total(state: TripState, travelers: int) -> Optional[float]:
    """Itinerary entry costs scaled to the party, or None if there is no plan."""
    itinerary = state.get("itinerary")
    days = itinerary.days if itinerary and itinerary.days else []
    if not days:
        return None
    per_person = sum(a.cost_usd for d in days for a in d.activities)
    return round(per_person * travelers, 2)


def activity_allowance(state: TripState) -> Optional[dict]:
    """What is left for activities once travel and lodging are paid for.

    Used by the itinerary agent, which runs after flight and hotels and so can
    plan against the real remainder rather than the headline budget.

    Feasibility is always judged against the CHEAPEST travel and lodging, even
    when the plan is costed at a different tier: if the floor already exceeds
    the budget, no choice of activities can rescue it, and the honest answer is
    to say the trip does not fit rather than to quietly plan a free itinerary
    and let the total come in over anyway.

    Returns None when no budget was given — there is then no cap to respect.
    """
    req = state["request"]
    if req.budget_usd is None:
        return None

    travelers = max(req.travelers, 1)
    night_count = nights(req)
    # floor, not the selected tier: this decides feasibility
    flights = flight_total(state, travelers, "cheapest")
    lodging = lodging_total(state, night_count, "cheapest")

    committed = (flights or 0.0) + (lodging or 0.0)
    unknown = [
        name
        for name, value in (("flights", flights), ("lodging", lodging))
        if value is None
    ]
    remaining = round(req.budget_usd - committed, 2)

    return {
        "budget_usd": req.budget_usd,
        "flights_usd": flights,
        "lodging_usd": lodging,
        "committed_usd": round(committed, 2),
        "remaining_usd": remaining,
        "per_person_per_day": round(remaining / travelers / max(night_count, 1), 2),
        # only meaningful once we actually know both floor costs
        "feasible": None if unknown else remaining >= 0,
        "unknown": unknown,
    }


def compute_breakdown(state: TripState) -> CostBreakdown:
    """Full breakdown for the budget agent. Pure and deterministic."""
    req = state["request"]
    travelers = max(req.travelers, 1)
    night_count = nights(req)
    tier = tier_for(req)

    flights = flight_total(state, travelers, tier)
    lodging = lodging_total(state, night_count, tier)
    activities = activities_total(state, travelers)

    missing = [
        name
        for name, value in (
            ("flights", flights),
            ("lodging", lodging),
            ("activities", activities),
        )
        if value is None
    ]

    travel_only = round((flights or 0.0) + (lodging or 0.0), 2)
    subtotal = round(travel_only + (activities or 0.0), 2)
    over_under = (
        round(subtotal - req.budget_usd, 2) if req.budget_usd is not None else None
    )

    # Feasibility is about the floor, not the costed tier: a mid-tier plan may
    # be over budget while a cheaper one still fits.
    feasible = None
    if req.budget_usd is not None:
        allowance = activity_allowance(state)
        feasible = allowance["feasible"] if allowance else None

    return CostBreakdown(
        travelers=travelers,
        nights=night_count,
        tier=tier,
        flights_usd=flights or 0.0,
        lodging_usd=lodging or 0.0,
        activities_usd=activities or 0.0,
        travel_only_usd=travel_only,
        subtotal_usd=subtotal,
        budget_usd=req.budget_usd,
        over_under_usd=over_under,
        within_budget=None if over_under is None else over_under <= 0,
        feasible=feasible,
        missing=missing,
    )
