"""What a run would cost at list price.

Every model this project uses is on a free tier, so the actual invoice is $0.
That is exactly why this exists: a number that only ever reads zero teaches
nobody anything, while "this plan would cost $0.019 at list price" is the figure
that decides whether the design survives contact with a paid account.

The rates are NOT hand-typed. They are lifted from the price map LiteLLM ships
(`litellm.model_cost`) — the same source the proxy uses to compute spend and
Langfuse uses to cost a trace, so the app's number and the observability stack's
number cannot quietly disagree. Refresh with `make prices` after upgrading
LiteLLM.

    generated by: scripts/refresh_prices.py
    source:       litellm 1.97.0, groq/* entries only
    units:        USD per token, input and output

An unknown model is priced as None, never as zero. Zero would silently claim a
run was free; None makes the gap visible and is counted as an unpriced call.
"""

# model id -> (usd per input token, usd per output token)
RATES: dict[str, tuple[float, float]] = {
    'groq/gemma-7b-it': (5e-08, 8e-08),
    'groq/llama-3.1-8b-instant': (5e-08, 8e-08),
    'groq/llama-3.3-70b-versatile': (5.9e-07, 7.9e-07),
    'groq/meta-llama/llama-4-maverick-17b-128e-instruct': (2e-07, 6e-07),
    'groq/meta-llama/llama-4-scout-17b-16e-instruct': (1.1e-07, 3.4e-07),
    'groq/meta-llama/llama-guard-4-12b': (2e-07, 2e-07),
    'groq/meta-llama/llama-prompt-guard-2-22m': (3e-08, 3e-08),
    'groq/meta-llama/llama-prompt-guard-2-86m': (4e-08, 4e-08),
    'groq/moonshotai/kimi-k2-instruct-0905': (1e-06, 3e-06),
    'groq/openai/gpt-oss-120b': (1.5e-07, 6e-07),
    'groq/openai/gpt-oss-20b': (7.5e-08, 3e-07),
    'groq/openai/gpt-oss-safeguard-20b': (7.5e-08, 3e-07),
    'groq/qwen/qwen3-32b': (2.9e-07, 5.9e-07),
    'groq/qwen/qwen3.6-27b': (6e-07, 3e-06),
}
