"""Regenerate `providers/prices.py` from LiteLLM's own price map.

Run through the Makefile, which pipes the map out of the running proxy:

    make prices

Two reasons it is generated rather than maintained by hand. Rates change, and a
hand-typed table drifts silently — the number keeps rendering, it is just wrong.
And the proxy already holds the authoritative map: taking the rates from there
means the figure the app shows and the figure LiteLLM bills against come from
one source, so they cannot disagree.

Reads the exported JSON on stdin: {"version": ..., "rates": {model: [in, out]}}.
"""

import json
import sys
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / "providers" / "prices.py"

HEADER = '''"""What a run would cost at list price.

Every model this project uses is on a free tier, so the actual invoice is $0.
That is exactly why this exists: a number that only ever reads zero teaches
nobody anything, while "this plan would cost $0.019 at list price" is the figure
that decides whether the design survives contact with a paid account.

The rates are NOT hand-typed. They are lifted from the price map LiteLLM ships
(`litellm.model_cost`) — the same source the proxy uses to compute spend and
Langfuse uses to cost a trace, so the app's number and the observability stack's
number cannot quietly disagree. Refresh with `make prices` after upgrading
LiteLLM.

    generated by: scripts/refresh_prices.py
    source:       litellm {version}, groq/* entries only
    units:        USD per token, input and output

An unknown model is priced as None, never as zero. Zero would silently claim a
run was free; None makes the gap visible and is counted as an unpriced call.
"""

# model id -> (usd per input token, usd per output token)
RATES: dict[str, tuple[float, float]] = {{
'''


def main() -> int:
    payload = json.load(sys.stdin)
    rates = {
        model: value
        for model, value in payload["rates"].items()
        if model.startswith("groq/")
    }
    if not rates:
        print("no groq/* rates in the export; refusing to write an empty table")
        return 1

    lines = [
        f"    {model!r}: ({value[0]!r}, {value[1]!r}),"
        for model, value in sorted(rates.items())
    ]
    TARGET.write_text(
        HEADER.format(version=payload.get("version", "unknown"))
        + "\n".join(lines)
        + "\n}\n"
    )
    print(f"wrote {len(rates)} rates to {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
